name: cineappflutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.2.0
  go_router: ^8.2.0
  json_serializable: ^6.7.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4

flutter:
  uses-material-design: true

  assets:
    - .env
